### ISSUE TITLE
Coach who registers for Multi-Team Event added as attendee instead of Team Leader

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#244]
When a coach registers for a multi-team event using the COACH registration function/code, he should be added as a TEAM LEADER to that team....not an attendee.

![image](https://user-images.githubusercontent.com/13508954/100551728-38635480-3248-11eb-94d7-b2e7f21097a5.png)

**Comment by timeforcamp** [comment]
resolved in current build.

**Comment by DENICHOLS** [comment]
Not quite resolved.

Account holder is being listed as the Team Leader even if another individual is registered as the coach by the account holder.

In my example, KIM was the account holder and she registered BO using the coach registration code.  

BO was listed as the coach in the attendee list, but KIM was listed as the Team Leader for the team and a user was created for KIM within the organization.

![image](https://user-images.githubusercontent.com/13508954/100696103-5ae49300-3358-11eb-9efb-f1d40f9d1997.png)
![image](https://user-images.githubusercontent.com/13508954/100696239-b9aa0c80-3358-11eb-8a76-98f82e72dadd.png)
![image](https://user-images.githubusercontent.com/13508954/100696184-98492080-3358-11eb-9e2c-8e89efec3c46.png)


All of these should have registered BO as the USER, TEAM LEADER (for the coach-f code in test), and as the COACH in the attendee screen.

**Comment by timeforcamp** [comment]
So your thinking that a coach’s mom is going to register them? In order to do what you are suggesting, which we have never had, would require the admin to invite Bo as and admin.

**Comment by timeforcamp** [comment]
resolved in latest build.
